name: Slack Send Message

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Slack Send Message
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          payload: '{
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "@channel Deploy *document-validator* \`v1.6.0\` em *Sandbox*"
                }
              }
            ]
          }'
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
