name: Slack Send Message

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest
    outputs:
      thread_ts: ${{ steps.thread_id.outputs.thread_ts }}
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Slack Send Message
        id: thread_id
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}

  slack-thread-start:
    runs-on: ubuntu-latest
    needs: slack
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Echo Thread ID
        run: echo ${{ needs.slack.outputs.thread_ts }}

      - name: Slack Send Message in Thread
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          thread_ts: ${{ needs.slack.outputs.thread_ts }}
          payload: 'start'
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}

  slack-thread-start2:
    runs-on: ubuntu-latest
    needs: slack
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Echo Thread ID
        run: echo ${{ needs.slack.outputs.thread_ts }}

      - name: Slack Send Message in Thread
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          thread_ts: ${{ needs.slack.outputs.thread_ts }}
          payload: 'start2'
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}

  slack-thread-start3:
    runs-on: ubuntu-latest
    needs: slack
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Echo Thread ID
        run: echo ${{ needs.slack.outputs.thread_ts }}

      - name: Slack Send Message in Thread
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          thread_ts: ${{ needs.slack.outputs.thread_ts }}
          payload: 'start3'

  slack-thread-finished:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [slack, slack-thread-start, slack-thread-start2, slack-thread-start3]
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Echo Thread ID
        run: echo ${{ needs.slack.outputs.thread_ts }}

      - name: Slack Send Message in Thread
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          thread_ts: ${{ needs.slack.outputs.thread_ts }}
          payload: 'finished'
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
