name: Slack Send Message

on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Slack Send Message
        id: thread_id
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}

      - name: Echo Thread ID
        run: echo ${{ steps.thread_id.outputs.thread_ts }}

  slack-thread:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v3

      - name: Echo Thread ID
        run: echo ${{ jobs.slack.steps.thread_id.outputs.thread_ts }}
